apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: scaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resourcetest
  updatePolicy:
    updateMode: "Auto"
